export const errorHandler=(error,req,res,next)=>{
console.log("Inside",error)
}